set( PROJECT_GEOS_NAME geos )
ExternalProject_Add(${PROJECT_GEOS_NAME}
   PREFIX ${PROJECT_GEOS_NAME}
   URL "https://github.com/libgeos/libgeos/archive/3.5.0.zip"
   INSTALL_DIR ${DEP_INSTALL_DIR}
   DOWNLOAD_DIR ${DEP_DOWNLOAD_DIR}/${PROJECT_GEOS_NAME}
   CMAKE_CACHE_ARGS -DGEOS_ENABLE_TESTS:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=${DEP_INSTALL_DIR}
)
